CREATE TYPE report_source_type AS ENUM ('normal', 'crawled');

CREATE TABLE reports (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id             VARCHAR,
    report_path            TEXT,
    format                 VARCHAR,
    create_dt              TIMESTAMPTZ,
    update_dt              TIMESTAMPTZ,
    create_user_id         VARCHAR,
    last_update_user_id    VARCHAR,
    title                  TEXT,
    category               VARCHAR,
    security_level         VARCHAR,
    identification_details TEXT,

    -- 파티션 키
    source_type            report_source_type NOT NULL,

    -- normal 전용 컬럼(다른 파티션에서는 NULL 가능)
    type        VARCHAR,

    -- crawled 전용 컬럼(다른 파티션에서는 NULL 가능)
    article_url TEXT,
    crawl_dt    TIMESTAMPTZ,
    source_site VARCHAR,
    raw_html    TEXT,

    -- ★ 파티션 키를 포함하는 PK
    PRIMARY KEY (source_type, id)
) PARTITION BY LIST (source_type);

-- normal 파티션
CREATE TABLE reports_normal
    PARTITION OF reports FOR VALUES IN ('normal');

CREATE INDEX idx_reports_type_createdt ON reports_normal (type, create_dt);
CREATE INDEX idx_reports_title         ON reports_normal (title);

-- crawled 파티션
CREATE TABLE reports_crawled
    PARTITION OF reports FOR VALUES IN ('crawled');

ALTER TABLE reports_crawled
  ADD CONSTRAINT reports_crawled_required_cols
  CHECK (article_url IS NOT NULL AND crawl_dt IS NOT NULL);

CREATE INDEX idx_reports_crawled_crawldt ON reports_crawled (crawl_dt);
CREATE INDEX idx_reports_article_url     ON reports_crawled (article_url);

-- (선택) id 단일 조회 최적화를 위한 파티션드(비고유) 인덱스
CREATE INDEX idx_reports_id ON reports (id);


-- targets table
CREATE TABLE IF NOT EXISTS targets (
  id          BIGSERIAL PRIMARY KEY,
  report_id   BIGINT NOT NULL,
  target_id   VARCHAR,
  category    VARCHAR,
  report_type VARCHAR,
  be_number   VARCHAR,
  mgrs        VARCHAR,
  latlon      JSONB,
  FOREIGN KEY (report_id) REFERENCES reports(id)
);

-- index creation for report_id of targets table
CREATE INDEX IF NOT EXISTS idx_targets_report_id ON targets (report_id);


-- imagery table
CREATE TABLE IF NOT EXISTS imagery (
  id                BIGSERIAL PRIMARY KEY,
  report_id         BIGINT NOT NULL,
  imagery_path      TEXT,
  acquisition_time  TIMESTAMPTZ,
  registration_time TIMESTAMPTZ,
  satellite         VARCHAR,
  coverage_wkt      TEXT,
  tilt_angle        NUMERIC,
  pitch_angle       NUMERIC,
  azimuth_angle     NUMERIC,
  FOREIGN KEY (report_id) REFERENCES reports(id)
);

CREATE INDEX IF NOT EXISTS idx_imagery_report_id ON imagery (report_id);
