# witness-compose.yaml

services:
  redis-sentinel3:
    image: redis:7.2-alpine
    container_name: redis-sentinel3
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    volumes:
      - ./redis/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    restart: always
