version: '3.8'

services:
  redis-master:
    image: redis:7.4.1-alpine
    container_name: redis-master
    command: redis-server --requirepass redis123 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-master-data:/data
    networks:
      - redis-net
    restart: unless-stopped

  redis-replica-1:
    image: redis:7.4.1-alpine
    container_name: redis-replica-1
    command: redis-server --replicaof redis-master 6379 --requirepass redis123 --masterauth redis123
    ports:
      - "6380:6379"
    volumes:
      - redis-replica-1-data:/data
    depends_on:
      - redis-master
    networks:
      - redis-net
    restart: unless-stopped

  redis-replica-2:
    image: redis:7.4.1-alpine
    container_name: redis-replica-2
    command: redis-server --replicaof redis-master 6379 --requirepass redis123 --masterauth redis123
    ports:
      - "6381:6379"
    volumes:
      - redis-replica-2-data:/data
    depends_on:
      - redis-master
    networks:
      - redis-net
    restart: unless-stopped

networks:
  redis-net:
    driver: bridge

volumes:
  redis-master-data:
  redis-replica-1-data:
  redis-replica-2-data:
